### ISSUE TITLE
Improve trigger matching

### ISSUE THREAD

**Issue by BrieucF** [cp3-llbb/HHAnalysis#44]
- [ ] Ensure that the two leptons have matched objects belonging to the same path
- [x] Also store the DeltaPt/PT
- [ ] Do the matching using the different path legs ?

**Comment by OlivierBondu** [comment]
the matching using different path legs is in no ?

**Comment by BrieucF** [comment]
I would'nt say so. With this line https://github.com/cp3-llbb/HHAnalysis/blob/master/plugins/HHAnalyzer.cc#L45 we are looping on all hlt_object to do the matching no matter the leg this object fired. On the other hand I have no feeling how important differenciating the legs is.

**Comment by blinkseb** [comment]
And I'm not sure how you do to know which leg your object fired? At least
what's needed is not saved by the framework for the moment...

2015-11-13 16:15 GMT+01:00 Brieuc Francois notifications@github.com:

> I would'nt say so. With this line
> https://github.com/cp3-llbb/HHAnalysis/blob/master/plugins/HHAnalyzer.cc#L45
> we are looping on all hlt_object to do the matching no matter the leg this
> object fired. On the other hand I have no feeling how important
> differenciating the legs is.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cp3-llbb/HHAnalysis/issues/44#issuecomment-156458602.

## 

Sébastien Brochet

**Comment by OlivierBondu** [comment]
Can someone confirm we can close this one ?

**Comment by BrieucF** [comment]
I'd like to keep this one open, the two items are not implemented yet. To me it is an enhancement good to keep in mind.

**Comment by pieterdavid** [comment]
I was not aware of this issue, but I also ran into some problems when adding single-lepton triggers at some point (turned out I don't urgently need them, but anyway... I think the problem was that the HLTProducer saves only an index per lepton or something like that - I don't remember all the details).
In case it may help: I moved the relevant pieces from the HLT producer and the trigger matching code in other analyzers together into https://github.com/pieterdavid/TTWAnalysis/blob/master/plugins/HLTDictTools.cc (mostly to keep a bit more overview). Making sure that they match objects from the same path becomes very easy then - I did not go as far as asking the legs to be different (if they are not too close together that should be fine anyway), but if the information is in the miniAOD, that should not be too difficult to add.

**Comment by pieterdavid** [comment]
After discussing with Olivier and looking into the code again, a small note with my previous comment: my problem was with the trigger matching as currently done in the TTAnalyzer (and also HHAnalyzer), not with the HLTProducer, and the only limitation is that they don't save enough information to compare single- and dilepton trigger efficiencies - so if you know what you want everything is fine in any case :-)
